### ISSUE TITLE
Firebase 4 update

### ISSUE THREAD

**Issue by dnnyg33** [popaaaandrei/RxFirebase#1]
It looks like firebase has released a new api version since this project last had any changes. I've updated the file to work most of the way, though i'm not sure about the NopDisposable. I could create a pull request if you'd add these changes.

**Comment by popaaaandrei** [comment]
Sure! I haven't updated the project in a while...

**Comment by 0xTea** [comment]
Hi  ,@dnnyg33  i  made a pull request with the changes  , i  made to the file . i used the RxSwift's Disposables class to achieve the functionality required for the new API . let me know if you have any success with it . I managed to sign in with version with  latest version of firebase.

**Comment by popaaaandrei** [comment]
I will make some changes as well, update the naming and get rid of NSData and NSURL.

**Comment by popaaaandrei** [comment]
Done. Added some improvements as well.
